# Generated by Django 4.2.6 on 2023-10-20 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff_data', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FacultyIds',
            new_name='FacultyId',
        ),
    ]
