# Generated by Django 4.2.6 on 2023-11-15 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff_data', '0003_campus_department_diversityacitivites_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facultyid',
            old_name='department',
            new_name='faculty_department',
        ),
        migrations.AddField(
            model_name='campus',
            name='faculty_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staff_data.facultyid'),
        ),
        migrations.AddField(
            model_name='department',
            name='faculty_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staff_data.facultyid'),
        ),
        migrations.AddField(
            model_name='diversityacitivites',
            name='faculty_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staff_data.facultyid'),
        ),
        migrations.AddField(
            model_name='diversityservice',
            name='faculty_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staff_data.facultyid'),
        ),
        migrations.AddField(
            model_name='diversityteaching',
            name='faculty_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staff_data.facultyid'),
        ),
        migrations.AddField(
            model_name='doctoralstudent',
            name='faculty_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staff_data.facultyid'),
        ),
        migrations.AddField(
            model_name='employmenthistory',
            name='faculty_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staff_data.facultyid'),
        ),
        migrations.AddField(
            model_name='honorsaward',
            name='faculty_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staff_data.facultyid'),
        ),
        migrations.AddField(
            model_name='masterstudent',
            name='faculty_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staff_data.facultyid'),
        ),
        migrations.AddField(
            model_name='membership',
            name='faculty_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staff_data.facultyid'),
        ),
        migrations.AddField(
            model_name='otheremployment',
            name='faculty_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staff_data.facultyid'),
        ),
        migrations.AddField(
            model_name='otherresearch',
            name='faculty_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staff_data.facultyid'),
        ),
        migrations.AddField(
            model_name='postdocstudent',
            name='faculty_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staff_data.facultyid'),
        ),
        migrations.AddField(
            model_name='profdevelopmentteaching',
            name='faculty_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staff_data.facultyid'),
        ),
        migrations.AddField(
            model_name='profdevservice',
            name='faculty_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staff_data.facultyid'),
        ),
        migrations.AddField(
            model_name='professionalactivity',
            name='faculty_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staff_data.facultyid'),
        ),
        migrations.AddField(
            model_name='professionaldevelopement',
            name='faculty_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staff_data.facultyid'),
        ),
        migrations.AddField(
            model_name='profpublicservice',
            name='faculty_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staff_data.facultyid'),
        ),
        migrations.AddField(
            model_name='school',
            name='faculty_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staff_data.facultyid'),
        ),
        migrations.AddField(
            model_name='teachingaward',
            name='faculty_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staff_data.facultyid'),
        ),
        migrations.AddField(
            model_name='teachinginnovation',
            name='faculty_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staff_data.facultyid'),
        ),
        migrations.AddField(
            model_name='ucicourse',
            name='faculty_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staff_data.facultyid'),
        ),
        migrations.AddField(
            model_name='undergradresearch',
            name='faculty_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staff_data.facultyid'),
        ),
        migrations.AddField(
            model_name='universitysystemwide',
            name='faculty_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staff_data.facultyid'),
        ),
    ]
