# Generated by Django 4.2.7 on 2023-11-24 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff_data', '0004_rename_department_facultyid_faculty_department_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campus',
            options={'verbose_name': 'Campus Service'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Department Service'},
        ),
        migrations.AlterModelOptions(
            name='diversityacitivites',
            options={'verbose_name': 'Diversity Activity Related to University/Systemwide Service', 'verbose_name_plural': 'Diversity Activities Related to University/Systemwide Service'},
        ),
        migrations.AlterModelOptions(
            name='employmenthistory',
            options={'verbose_name': 'Employment History', 'verbose_name_plural': 'Employment Histories'},
        ),
        migrations.AlterModelOptions(
            name='otheremployment',
            options={'verbose_name': 'Other Employment'},
        ),
        migrations.AlterModelOptions(
            name='professionaldevelopement',
            options={'verbose_name': 'Professional Development Activity Related to University/Systemwide Service', 'verbose_name_plural': 'Professional Development Activities Related to University/Systemwide Service'},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'verbose_name': 'School Service'},
        ),
        migrations.AlterModelOptions(
            name='universitysystemwide',
            options={'verbose_name': 'University/Systemwide Service'},
        ),
        migrations.AlterField(
            model_name='campus',
            name='period_end',
            field=models.DateField(verbose_name='Period End'),
        ),
        migrations.AlterField(
            model_name='campus',
            name='period_start',
            field=models.DateField(verbose_name='Period Start'),
        ),
        migrations.AlterField(
            model_name='campus',
            name='position_description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='department',
            name='period_end',
            field=models.DateField(verbose_name='Period End'),
        ),
        migrations.AlterField(
            model_name='department',
            name='period_start',
            field=models.DateField(verbose_name='Period Start'),
        ),
        migrations.AlterField(
            model_name='department',
            name='position_description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='diversityacitivites',
            name='period_end',
            field=models.DateField(verbose_name='Period End'),
        ),
        migrations.AlterField(
            model_name='diversityacitivites',
            name='period_start',
            field=models.DateField(verbose_name='Period Start'),
        ),
        migrations.AlterField(
            model_name='diversityacitivites',
            name='position_description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='diversityservice',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='diversityteaching',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='doctoralstudent',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='employmenthistory',
            name='period_end',
            field=models.DateField(verbose_name='Period End'),
        ),
        migrations.AlterField(
            model_name='employmenthistory',
            name='period_start',
            field=models.DateField(verbose_name='Period Start'),
        ),
        migrations.AlterField(
            model_name='employmenthistory',
            name='time_percentage',
            field=models.DecimalField(decimal_places=0, max_digits=3, verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='employmenthistory',
            name='title_rank',
            field=models.CharField(max_length=100, verbose_name='Title & Rank'),
        ),
        migrations.AlterField(
            model_name='honorsaward',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='masterstudent',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='otheremployment',
            name='period_end',
            field=models.DateField(verbose_name='Period End'),
        ),
        migrations.AlterField(
            model_name='otheremployment',
            name='period_start',
            field=models.DateField(verbose_name='Period Start'),
        ),
        migrations.AlterField(
            model_name='otheremployment',
            name='position_description',
            field=models.TextField(verbose_name='Position/Description'),
        ),
        migrations.AlterField(
            model_name='otherresearch',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='postdocstudent',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='profdevelopmentteaching',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='profdevservice',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='professionalactivity',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='professionaldevelopement',
            name='period_end',
            field=models.DateField(verbose_name='Period End'),
        ),
        migrations.AlterField(
            model_name='professionaldevelopement',
            name='period_start',
            field=models.DateField(verbose_name='Period Start'),
        ),
        migrations.AlterField(
            model_name='professionaldevelopement',
            name='position_description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='profpublicservice',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='school',
            name='period_end',
            field=models.DateField(verbose_name='Period End'),
        ),
        migrations.AlterField(
            model_name='school',
            name='period_start',
            field=models.DateField(verbose_name='Period Start'),
        ),
        migrations.AlterField(
            model_name='school',
            name='position_description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='teachingaward',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='teachinginnovation',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='undergradresearch',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='universitysystemwide',
            name='period_end',
            field=models.DateField(verbose_name='Period End'),
        ),
        migrations.AlterField(
            model_name='universitysystemwide',
            name='period_start',
            field=models.DateField(verbose_name='Period Start'),
        ),
        migrations.AlterField(
            model_name='universitysystemwide',
            name='position_description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.CreateModel(
            name='ProfessionalResources',
            fields=[
                ('internalID', models.AutoField(primary_key=True, serialize=False)),
                ('dates_active', models.CharField(max_length=100, verbose_name='Date(s) Active')),
                ('description', models.TextField()),
                ('faculty_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staff_data.facultyid')),
            ],
            options={
                'verbose_name': 'Professional Online & System Resource Produced/Maintained',
                'verbose_name_plural': 'Professional Online & System Resources Produced/Maintained',
            },
        ),
        migrations.CreateModel(
            name='ProfDevResearchActivities',
            fields=[
                ('internalID', models.AutoField(primary_key=True, serialize=False)),
                ('dates', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('faculty_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staff_data.facultyid')),
            ],
            options={
                'verbose_name': 'Professional Development Activity Related to Research/Creative Activity',
                'verbose_name_plural': 'Professional Development Activities Related to Research/Creative Activities',
            },
        ),
        migrations.CreateModel(
            name='PreviousContributions',
            fields=[
                ('internalID', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100)),
                ('publication_citation', models.TextField(verbose_name='Publication')),
                ('date', models.DateField()),
                ('faculty_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staff_data.facultyid')),
            ],
            options={
                'verbose_name': 'Intellectual Contributions (Previously Submitted in a Prior Review)',
            },
        ),
        migrations.CreateModel(
            name='NotCreditedArtistic',
            fields=[
                ('internalID', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100)),
                ('creativeWork', models.TextField(verbose_name='Creative Work')),
                ('date', models.DateField()),
                ('faculty_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staff_data.facultyid')),
            ],
            options={
                'verbose_name': 'Artistic and Professional Performance and Exhibit (Not Credited in a Prior Review)',
                'verbose_name_plural': 'Artistic and Professional Performances and Exhibits (Not Credited in a Prior Review)',
            },
        ),
        migrations.CreateModel(
            name='NonFinancialResources',
            fields=[
                ('internalID', models.AutoField(primary_key=True, serialize=False)),
                ('previously_submitted', models.BooleanField(verbose_name='Previously Submitted')),
                ('funding_source', models.CharField(max_length=200, verbose_name='Funding Source')),
                ('number_or_title', models.CharField(max_length=100, verbose_name='Number or Title')),
                ('role', models.CharField(max_length=100)),
                ('perks_description', models.TextField(verbose_name='Amount')),
                ('date_span', models.CharField(max_length=100, verbose_name='Date Span of Award')),
                ('faculty_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staff_data.facultyid')),
            ],
            options={
                'verbose_name': 'Allocation of Other Non-Financial Resource',
            },
        ),
        migrations.CreateModel(
            name='IntellectualProperty',
            fields=[
                ('internalID', models.AutoField(primary_key=True, serialize=False)),
                ('dates', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('faculty_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staff_data.facultyid')),
            ],
            options={
                'verbose_name': 'Intellectual Property - Patent, Copyright, Etc.',
                'verbose_name_plural': 'Intellectual Property - Patents, Copyrights, Etc.',
            },
        ),
        migrations.CreateModel(
            name='IntellectualContributions',
            fields=[
                ('internalID', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100)),
                ('publication_citation', models.TextField(verbose_name='Publication')),
                ('date', models.DateField()),
                ('faculty_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staff_data.facultyid')),
            ],
            options={
                'verbose_name': 'Intellectual Contributions (Not Credited in a Prior Review)',
            },
        ),
        migrations.CreateModel(
            name='DiversityResearchActivities',
            fields=[
                ('internalID', models.AutoField(primary_key=True, serialize=False)),
                ('dates', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('faculty_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staff_data.facultyid')),
            ],
            options={
                'verbose_name': 'Diversity Activity Related to Research/Creative Activity',
                'verbose_name_plural': 'Diversity Activities Related to Research/Creative Activities',
            },
        ),
        migrations.CreateModel(
            name='CreditedArtistic',
            fields=[
                ('internalID', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100)),
                ('creativeWork', models.TextField(verbose_name='Creative Work')),
                ('date', models.DateField()),
                ('faculty_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staff_data.facultyid')),
            ],
            options={
                'verbose_name': 'Artistic and Professional Performance and Exhibit (Previously Submitted in a Prior Review)',
                'verbose_name_plural': 'Artistic and Professional Performances and Exhibits (Previously Submitted in a Prior Review)',
            },
        ),
        migrations.CreateModel(
            name='ContractsGrantsFellowships',
            fields=[
                ('internalID', models.AutoField(primary_key=True, serialize=False)),
                ('previously_submitted', models.BooleanField(verbose_name='Previously Submitted')),
                ('funding_source', models.CharField(max_length=200, verbose_name='Funding Source')),
                ('number_or_title', models.CharField(max_length=100, verbose_name='Number or Title')),
                ('role', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_span', models.CharField(max_length=100, verbose_name='Date Span of Award')),
                ('faculty_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staff_data.facultyid')),
            ],
            options={
                'verbose_name': 'Contract, Grant, Fellowship',
                'verbose_name_plural': 'Contracts, Grants, Fellowships',
            },
        ),
        migrations.CreateModel(
            name='CompletedPartsOfWorks',
            fields=[
                ('internalID', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100)),
                ('work_detail', models.TextField(verbose_name='Publication or Creative Work')),
                ('faculty_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staff_data.facultyid')),
            ],
            options={
                'verbose_name': 'Completed Part of Larger Work',
                'verbose_name_plural': 'Completed Parts of Larger Works',
            },
        ),
    ]
