# Generated by Django 4.2.6 on 2023-12-08 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff_data', '0005_alter_campus_options_alter_department_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campus',
            old_name='employment_id',
            new_name='internalID',
        ),
        migrations.RenameField(
            model_name='department',
            old_name='employment_id',
            new_name='internalID',
        ),
        migrations.RenameField(
            model_name='diversityacitivites',
            old_name='employment_id',
            new_name='internalID',
        ),
        migrations.RenameField(
            model_name='professionaldevelopement',
            old_name='employment_id',
            new_name='internalID',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='employment_id',
            new_name='internalID',
        ),
        migrations.RenameField(
            model_name='universitysystemwide',
            old_name='employment_id',
            new_name='internalID',
        ),
    ]
