# Generated by Django 4.2.7 on 2023-12-15 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_data', '0006_rename_employment_id_campus_internalid_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ucicourse',
            name='quarter_year_pair',
        ),
        migrations.RemoveField(
            model_name='contractsgrantsfellowships',
            name='date_span',
        ),
        migrations.RemoveField(
            model_name='creditedartistic',
            name='date',
        ),
        migrations.RemoveField(
            model_name='diversityresearchactivities',
            name='dates',
        ),
        migrations.RemoveField(
            model_name='diversityservice',
            name='dateinput',
        ),
        migrations.RemoveField(
            model_name='diversityservice',
            name='enddate',
        ),
        migrations.RemoveField(
            model_name='diversityservice',
            name='startdate',
        ),
        migrations.RemoveField(
            model_name='diversityteaching',
            name='dateinput',
        ),
        migrations.RemoveField(
            model_name='diversityteaching',
            name='enddate',
        ),
        migrations.RemoveField(
            model_name='diversityteaching',
            name='startdate',
        ),
        migrations.RemoveField(
            model_name='doctoralstudent',
            name='endyear',
        ),
        migrations.RemoveField(
            model_name='doctoralstudent',
            name='startyear',
        ),
        migrations.RemoveField(
            model_name='honorsaward',
            name='dateinput',
        ),
        migrations.RemoveField(
            model_name='honorsaward',
            name='enddate',
        ),
        migrations.RemoveField(
            model_name='honorsaward',
            name='startdate',
        ),
        migrations.RemoveField(
            model_name='intellectualcontributions',
            name='date',
        ),
        migrations.RemoveField(
            model_name='intellectualproperty',
            name='dates',
        ),
        migrations.RemoveField(
            model_name='masterstudent',
            name='endyear',
        ),
        migrations.RemoveField(
            model_name='masterstudent',
            name='startyear',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='dateinput',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='enddate',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='startdate',
        ),
        migrations.RemoveField(
            model_name='nonfinancialresources',
            name='date_span',
        ),
        migrations.RemoveField(
            model_name='notcreditedartistic',
            name='date',
        ),
        migrations.RemoveField(
            model_name='otherresearch',
            name='endyear',
        ),
        migrations.RemoveField(
            model_name='otherresearch',
            name='startyear',
        ),
        migrations.RemoveField(
            model_name='postdocstudent',
            name='endyear',
        ),
        migrations.RemoveField(
            model_name='postdocstudent',
            name='startyear',
        ),
        migrations.RemoveField(
            model_name='previouscontributions',
            name='date',
        ),
        migrations.RemoveField(
            model_name='profdevelopmentteaching',
            name='dateinput',
        ),
        migrations.RemoveField(
            model_name='profdevelopmentteaching',
            name='enddate',
        ),
        migrations.RemoveField(
            model_name='profdevelopmentteaching',
            name='startdate',
        ),
        migrations.RemoveField(
            model_name='profdevresearchactivities',
            name='dates',
        ),
        migrations.RemoveField(
            model_name='profdevservice',
            name='dateinput',
        ),
        migrations.RemoveField(
            model_name='profdevservice',
            name='enddate',
        ),
        migrations.RemoveField(
            model_name='profdevservice',
            name='startdate',
        ),
        migrations.RemoveField(
            model_name='professionalactivity',
            name='dateinput',
        ),
        migrations.RemoveField(
            model_name='professionalactivity',
            name='enddate',
        ),
        migrations.RemoveField(
            model_name='professionalactivity',
            name='startdate',
        ),
        migrations.RemoveField(
            model_name='professionalresources',
            name='dates_active',
        ),
        migrations.RemoveField(
            model_name='profpublicservice',
            name='dateinput',
        ),
        migrations.RemoveField(
            model_name='profpublicservice',
            name='enddate',
        ),
        migrations.RemoveField(
            model_name='profpublicservice',
            name='startdate',
        ),
        migrations.RemoveField(
            model_name='teachingaward',
            name='dateinput',
        ),
        migrations.RemoveField(
            model_name='teachingaward',
            name='enddate',
        ),
        migrations.RemoveField(
            model_name='teachingaward',
            name='startdate',
        ),
        migrations.RemoveField(
            model_name='teachinginnovation',
            name='dateinput',
        ),
        migrations.RemoveField(
            model_name='teachinginnovation',
            name='enddate',
        ),
        migrations.RemoveField(
            model_name='teachinginnovation',
            name='startdate',
        ),
        migrations.RemoveField(
            model_name='ucicourse',
            name='quarter',
        ),
        migrations.RemoveField(
            model_name='ucicourse',
            name='year',
        ),
        migrations.RemoveField(
            model_name='undergradresearch',
            name='endyear',
        ),
        migrations.RemoveField(
            model_name='undergradresearch',
            name='startyear',
        ),
        migrations.AddField(
            model_name='completedpartsofworks',
            name='period_end',
            field=models.DateField(null=True, verbose_name='Period End'),
        ),
        migrations.AddField(
            model_name='completedpartsofworks',
            name='period_start',
            field=models.DateField(null=True, verbose_name='Period Start'),
        ),
        migrations.AddField(
            model_name='contractsgrantsfellowships',
            name='period_end',
            field=models.DateField(null=True, verbose_name='Period End'),
        ),
        migrations.AddField(
            model_name='contractsgrantsfellowships',
            name='period_start',
            field=models.DateField(null=True, verbose_name='Period Start'),
        ),
        migrations.AddField(
            model_name='creditedartistic',
            name='period_end',
            field=models.DateField(null=True, verbose_name='Period End'),
        ),
        migrations.AddField(
            model_name='creditedartistic',
            name='period_start',
            field=models.DateField(null=True, verbose_name='Period Start'),
        ),
        migrations.AddField(
            model_name='diversityresearchactivities',
            name='period_end',
            field=models.DateField(null=True, verbose_name='Period End'),
        ),
        migrations.AddField(
            model_name='diversityresearchactivities',
            name='period_start',
            field=models.DateField(null=True, verbose_name='Period Start'),
        ),
        migrations.AddField(
            model_name='diversityservice',
            name='period_end',
            field=models.DateField(null=True, verbose_name='Period End'),
        ),
        migrations.AddField(
            model_name='diversityservice',
            name='period_start',
            field=models.DateField(null=True, verbose_name='Period Start'),
        ),
        migrations.AddField(
            model_name='diversityteaching',
            name='period_end',
            field=models.DateField(null=True, verbose_name='Period End'),
        ),
        migrations.AddField(
            model_name='diversityteaching',
            name='period_start',
            field=models.DateField(null=True, verbose_name='Period Start'),
        ),
        migrations.AddField(
            model_name='doctoralstudent',
            name='period_end',
            field=models.DateField(null=True, verbose_name='Period End'),
        ),
        migrations.AddField(
            model_name='doctoralstudent',
            name='period_start',
            field=models.DateField(null=True, verbose_name='Period Start'),
        ),
        migrations.AddField(
            model_name='honorsaward',
            name='period_end',
            field=models.DateField(null=True, verbose_name='Period End'),
        ),
        migrations.AddField(
            model_name='honorsaward',
            name='period_start',
            field=models.DateField(null=True, verbose_name='Period Start'),
        ),
        migrations.AddField(
            model_name='intellectualcontributions',
            name='period_end',
            field=models.DateField(null=True, verbose_name='Period End'),
        ),
        migrations.AddField(
            model_name='intellectualcontributions',
            name='period_start',
            field=models.DateField(null=True, verbose_name='Period Start'),
        ),
        migrations.AddField(
            model_name='intellectualproperty',
            name='period_end',
            field=models.DateField(null=True, verbose_name='Period End'),
        ),
        migrations.AddField(
            model_name='intellectualproperty',
            name='period_start',
            field=models.DateField(null=True, verbose_name='Period Start'),
        ),
        migrations.AddField(
            model_name='masterstudent',
            name='period_end',
            field=models.DateField(null=True, verbose_name='Period End'),
        ),
        migrations.AddField(
            model_name='masterstudent',
            name='period_start',
            field=models.DateField(null=True, verbose_name='Period Start'),
        ),
        migrations.AddField(
            model_name='membership',
            name='period_end',
            field=models.DateField(null=True, verbose_name='Period End'),
        ),
        migrations.AddField(
            model_name='membership',
            name='period_start',
            field=models.DateField(null=True, verbose_name='Period Start'),
        ),
        migrations.AddField(
            model_name='nonfinancialresources',
            name='period_end',
            field=models.DateField(null=True, verbose_name='Period End'),
        ),
        migrations.AddField(
            model_name='nonfinancialresources',
            name='period_start',
            field=models.DateField(null=True, verbose_name='Period Start'),
        ),
        migrations.AddField(
            model_name='notcreditedartistic',
            name='period_end',
            field=models.DateField(null=True, verbose_name='Period End'),
        ),
        migrations.AddField(
            model_name='notcreditedartistic',
            name='period_start',
            field=models.DateField(null=True, verbose_name='Period Start'),
        ),
        migrations.AddField(
            model_name='otherresearch',
            name='period_end',
            field=models.DateField(null=True, verbose_name='Period End'),
        ),
        migrations.AddField(
            model_name='otherresearch',
            name='period_start',
            field=models.DateField(null=True, verbose_name='Period Start'),
        ),
        migrations.AddField(
            model_name='postdocstudent',
            name='period_end',
            field=models.DateField(null=True, verbose_name='Period End'),
        ),
        migrations.AddField(
            model_name='postdocstudent',
            name='period_start',
            field=models.DateField(null=True, verbose_name='Period Start'),
        ),
        migrations.AddField(
            model_name='previouscontributions',
            name='period_end',
            field=models.DateField(null=True, verbose_name='Period End'),
        ),
        migrations.AddField(
            model_name='previouscontributions',
            name='period_start',
            field=models.DateField(null=True, verbose_name='Period Start'),
        ),
        migrations.AddField(
            model_name='profdevelopmentteaching',
            name='period_end',
            field=models.DateField(null=True, verbose_name='Period End'),
        ),
        migrations.AddField(
            model_name='profdevelopmentteaching',
            name='period_start',
            field=models.DateField(null=True, verbose_name='Period Start'),
        ),
        migrations.AddField(
            model_name='profdevresearchactivities',
            name='period_end',
            field=models.DateField(null=True, verbose_name='Period End'),
        ),
        migrations.AddField(
            model_name='profdevresearchactivities',
            name='period_start',
            field=models.DateField(null=True, verbose_name='Period Start'),
        ),
        migrations.AddField(
            model_name='profdevservice',
            name='period_end',
            field=models.DateField(null=True, verbose_name='Period End'),
        ),
        migrations.AddField(
            model_name='profdevservice',
            name='period_start',
            field=models.DateField(null=True, verbose_name='Period Start'),
        ),
        migrations.AddField(
            model_name='professionalactivity',
            name='period_end',
            field=models.DateField(null=True, verbose_name='Period End'),
        ),
        migrations.AddField(
            model_name='professionalactivity',
            name='period_start',
            field=models.DateField(null=True, verbose_name='Period Start'),
        ),
        migrations.AddField(
            model_name='professionalresources',
            name='period_end',
            field=models.DateField(null=True, verbose_name='Period End'),
        ),
        migrations.AddField(
            model_name='professionalresources',
            name='period_start',
            field=models.DateField(null=True, verbose_name='Period Start'),
        ),
        migrations.AddField(
            model_name='profpublicservice',
            name='period_end',
            field=models.DateField(null=True, verbose_name='Period End'),
        ),
        migrations.AddField(
            model_name='profpublicservice',
            name='period_start',
            field=models.DateField(null=True, verbose_name='Period Start'),
        ),
        migrations.AddField(
            model_name='teachingaward',
            name='period_end',
            field=models.DateField(null=True, verbose_name='Period End'),
        ),
        migrations.AddField(
            model_name='teachingaward',
            name='period_start',
            field=models.DateField(null=True, verbose_name='Period Start'),
        ),
        migrations.AddField(
            model_name='teachinginnovation',
            name='period_end',
            field=models.DateField(null=True, verbose_name='Period End'),
        ),
        migrations.AddField(
            model_name='teachinginnovation',
            name='period_start',
            field=models.DateField(null=True, verbose_name='Period Start'),
        ),
        migrations.AddField(
            model_name='ucicourse',
            name='period_end',
            field=models.DateField(null=True, verbose_name='Period End'),
        ),
        migrations.AddField(
            model_name='ucicourse',
            name='period_start',
            field=models.DateField(null=True, verbose_name='Period Start'),
        ),
        migrations.AddField(
            model_name='undergradresearch',
            name='period_end',
            field=models.DateField(null=True, verbose_name='Period End'),
        ),
        migrations.AddField(
            model_name='undergradresearch',
            name='period_start',
            field=models.DateField(null=True, verbose_name='Period Start'),
        ),
        migrations.AlterField(
            model_name='campus',
            name='period_end',
            field=models.DateField(null=True, verbose_name='Period End'),
        ),
        migrations.AlterField(
            model_name='campus',
            name='period_start',
            field=models.DateField(null=True, verbose_name='Period Start'),
        ),
        migrations.AlterField(
            model_name='department',
            name='period_end',
            field=models.DateField(null=True, verbose_name='Period End'),
        ),
        migrations.AlterField(
            model_name='department',
            name='period_start',
            field=models.DateField(null=True, verbose_name='Period Start'),
        ),
        migrations.AlterField(
            model_name='diversityacitivites',
            name='period_end',
            field=models.DateField(null=True, verbose_name='Period End'),
        ),
        migrations.AlterField(
            model_name='diversityacitivites',
            name='period_start',
            field=models.DateField(null=True, verbose_name='Period Start'),
        ),
        migrations.AlterField(
            model_name='employmenthistory',
            name='period_end',
            field=models.DateField(null=True, verbose_name='Period End'),
        ),
        migrations.AlterField(
            model_name='employmenthistory',
            name='period_start',
            field=models.DateField(null=True, verbose_name='Period Start'),
        ),
        migrations.AlterField(
            model_name='otheremployment',
            name='period_end',
            field=models.DateField(null=True, verbose_name='Period End'),
        ),
        migrations.AlterField(
            model_name='otheremployment',
            name='period_start',
            field=models.DateField(null=True, verbose_name='Period Start'),
        ),
        migrations.AlterField(
            model_name='professionaldevelopement',
            name='period_end',
            field=models.DateField(null=True, verbose_name='Period End'),
        ),
        migrations.AlterField(
            model_name='professionaldevelopement',
            name='period_start',
            field=models.DateField(null=True, verbose_name='Period Start'),
        ),
        migrations.AlterField(
            model_name='school',
            name='period_end',
            field=models.DateField(null=True, verbose_name='Period End'),
        ),
        migrations.AlterField(
            model_name='school',
            name='period_start',
            field=models.DateField(null=True, verbose_name='Period Start'),
        ),
        migrations.AlterField(
            model_name='universitysystemwide',
            name='period_end',
            field=models.DateField(null=True, verbose_name='Period End'),
        ),
        migrations.AlterField(
            model_name='universitysystemwide',
            name='period_start',
            field=models.DateField(null=True, verbose_name='Period Start'),
        ),
    ]
